# 다항(Polynomial)회귀

- 독립변수가 단항식이 아닌 2차,3차 방식식과 같은 다항식으로 표현되는 것
- 다항회귀는 **선형회귀**
- 선형/비선형 나누는 기준 : 회귀계수가 선형인지 비선형인지에 따른 것


## 1차단항식 -> 2차다항식 변환

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# 다항식으로 변환할 단항식 생성
X = np.arange(4).reshape(2,2)
print('1차 단항식 피처:\n',X)

#degree = 2 인 2차 다항식으로 변환하기 위해 Polynomial Features이용

poly = PolynomialFeatures(degree=2)
poly.fit(X)
poly_ftr = poly.transform(X)
print('변환된 2차 다항식 피처:\n ',poly_ftr)

1차 단항식 피처:
 [[0 1]
 [2 3]]
변환된 2차 다항식 피처:
  [[1. 0. 1. 0. 0. 1.]
 [1. 2. 3. 4. 6. 9.]]


## 3차 다항 회귀 함수 임의설정 후 회귀계수 예측

In [2]:
def polynomial_func(X):
    y = 1 + 2*X[:,0] + 3*X[:,0]**2 + 4*X[:,1]**3
    return y

X = np.arange(4).reshape(2,2)
print('1차 다항식 계수 feature::\n',X)
y = polynomial_func(X)
print('3차 다항식 결정값::\n',y)

1차 다항식 계수 feature::
 [[0 1]
 [2 3]]
3차 다항식 결정값::
 [  5 125]


## 일차 단항식 계수 -> 삼차 다항식 계수변환, 선형회귀 적용으로 다항회귀 구현

In [3]:
from sklearn.linear_model import LinearRegression
poly_ftr = PolynomialFeatures(degree=3).fit_transform(X)
print('3차 다항식 계수 feature:\n', poly_ftr)

model = LinearRegression()
model.fit(poly_ftr,y)
print('Polynomial 회귀 계수: ', np.round(model.coef_,2))
print('Polynomial 회귀 Shape : ', model.coef_.shape)

3차 다항식 계수 feature:
 [[ 1.  0.  1.  0.  0.  1.  0.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.  8. 12. 18. 27.]]
Polynomial 회귀 계수:  [0.   0.18 0.18 0.36 0.54 0.72 0.72 1.08 1.62 2.34]
Polynomial 회귀 Shape :  (10,)


In [6]:
# Pipeline 활용
from sklearn.pipeline import Pipeline

def Polynomial_func(X):
    y = 1 + 2*X[:,0] + 3*X[:,0]**2 + 4*X[:,0]**3
    return

model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                 ('Linear',LinearRegression())])

X = np.arange(4).reshape(2,2)
y = polynomial_func(X)
model = model.fit(X,y)
print('Polynomial 회귀 계수:\n', np.round(model.named_steps['Linear'].coef_,2))

Polynomial 회귀 계수:
 [0.   0.18 0.18 0.36 0.54 0.72 0.72 1.08 1.62 2.34]
